### ISSUE TITLE
Selector issue

### ISSUE THREAD

**Issue by zoechi** [GoogleWebComponents/google-feeds#16]
https://github.com/GoogleWebComponents/google-feeds/blob/master/demo/index.html#L26 is not the div element the message(s) are added, but instead to a dynamically added 

``` html
<div id="content" class="style-scope google-feeds">
  <div class="gfc-control"><div class="gfc-resultsbox-visible">
  </div></div>
  google-feeds loaded<br>
</div>
```

**Comment by ebidel** [comment]
Can you clarify?

**Comment by zoechi** [comment]
The `document.querySelector('div')` doesn't select the `</div></div>` (which I guess was intended) but some dynamically inserted div element.

**Comment by zoechi** [comment]
It seems this `<div>` was added as an anchor to add the messages here https://github.com/GoogleWebComponents/google-feeds/blob/master/demo/index.html#L31
but the selector finds another `<div>` on the page. Not sure where this comes from though but it results in the messages being added on top of the page instead of the bottom.
