### ISSUE TITLE
Do a pass through for code-style (indentation, quote-style etc)

### ISSUE THREAD

**Issue by addyosmani** [GoogleWebComponents/google-feeds#9]
As this element was rather hastily put together over the weekend, I'll go through and improve the overall code-style once the docs work in #8 lands.

**Comment by addyosmani** [comment]
cc @arthurvr

**Comment by arthurvr** [comment]
Sorry for always being the one complaining about a pair of double quotes :) If you tell me what style guide we use I can PR this one.

**Comment by addyosmani** [comment]
Not at all! It keeps us honest :) Generally we try to follow the Google JS style guide. The [signin](https://github.com/GoogleWebComponents/google-signin/blob/master/google-signin.html) element is a good example of where this should be code style wise.

**Comment by arthurvr** [comment]
Should probably include an editorconfig as well. Is there a reason you're not using it in any of the repos here?

**Comment by addyosmani** [comment]
We use release scripts to strip away dev config files for the other Polymer elements, but don't yet do this for any of the GWC collection. I would suggest we look into adding EC files in the mid-term.
